// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASWElrVJjbYNxLF8Yb6uxdaIilPaL-dFc',
    appId: '1:499256183029:android:52833e1761360134f05dbc',
    messagingSenderId: '499256183029',
    projectId: 'parametric-b1ee1',
    storageBucket: 'parametric-b1ee1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiPZTYslEBhc8meTeuFwvlgxAmmCcv2fI',
    appId: '1:499256183029:ios:ef2a6c325927228bf05dbc',
    messagingSenderId: '499256183029',
    projectId: 'parametric-b1ee1',
    storageBucket: 'parametric-b1ee1.appspot.com',
    iosClientId: '499256183029-84bf5jic1vs3h5gsrdhtbtfqr67q924m.apps.googleusercontent.com',
    iosBundleId: 'com.parametric.app',
  );
}
